name: Build and Deploy Astro Blog

on:
  push:
    branches:
      - main
    paths:
      - 'public/data/runs/**.json'
      - 'src/**'
      - 'public/**'
      - 'astro.config.*'
      - 'package.json'
      - 'tsconfig.json'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Clean previous builds
        run: rm -rf dist

      - name: Build the site
        run: npm run build

      - name: List contents of /dist (debug)
        run: find dist/ -type f

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
