name: Build and Deploy Astro Blog

on:
  push:
    branches:
      - main
    paths:
      - 'public/**'
      - 'src/**'
      - 'astro.config.*'
      - 'vite.config.*'
      - 'package.json'
      - 'tsconfig.json'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clean dist
        run: rm -rf dist

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Wait before deployment
        run: sleep 5

      - name: Debug output
        run: |
          echo "✅ Showing all files in /dist:"
          find dist/ -type f

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
